### ISSUE TITLE
openMSX flatpak support

### ISSUE THREAD

**Issue by rderooy** [openMSX/openMSX#1291]
I have created a flatpak for openMSX that I'm wanting to push to flathub. But before doing so, I want to ask a few questions.

1. Do you have any issues with me doing this? I have done a flatpak for another project before. If you do, I can provide you with the files and instructions such that you can push it yourself.
2. assuming your OK with me pushing this, which devs here should I add to the project such that I'm not the only one that can update it when a new release is out.
3. while the flatpak builds and runs, I have an issue with the opengl detection, and am hoping that someone here can point me in the right direction.

In particular, here is the error I get in probe.log:
```
GL: Found header
GL: Found lib
GLEW: Found header
linker command: g++ derived/x86_64-linux-opt/config/GLEW.o -o derived/x86_64-linux-opt/config/GLEW.bin -m64 -lGLEW
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lGLEW
collect2: error: ld returned 1 exit status
return code from linker: 1
GLEW: Missing lib
```

If I open a shell into the sandbox environment that is used for the build, here are the libs:
```
bash-5.0$ env|grep LIBRARY
LD_LIBRARY_PATH=/app/lib:/usr/lib/x86_64-linux-gnu/GL/default/lib:/usr/lib/x86_64-linux-gnu/openh264/extra
bash-5.0$ ls -l /app/lib/
total 11592
drwxr-xr-x 4 robert robert     4096 Jan  1  1970 debug
drwxr-xr-x 2 robert robert     4096 Jan  1  1970 itcl4.2.0
lrwxrwxrwx 1 robert robert       16 Jan  1  1970 libGLEW.so -> libGLEW.so.2.2.0
lrwxrwxrwx 1 robert robert       16 Jan  1  1970 libGLEW.so.2.2 -> libGLEW.so.2.2.0
-rw-r--r-- 2 robert robert   735344 Jan  1  1970 libGLEW.so.2.2.0
lrwxrwxrwx 1 robert robert       15 Jan  1  1970 libGLU.so -> libGLU.so.1.3.1
lrwxrwxrwx 1 robert robert       15 Jan  1  1970 libGLU.so.1 -> libGLU.so.1.3.1
-rwxr-xr-x 2 robert robert   477384 Jan  1  1970 libGLU.so.1.3.1
-rwxr-xr-x 2 robert robert 10597088 Jan  1  1970 libtcl8.6.so
drwxr-xr-x 2 robert robert     4096 Jan  1  1970 sqlite3.30.1.2
drwxr-xr-x 5 robert robert     4096 Jan  1  1970 tcl8
drwxr-xr-x 6 robert robert     4096 Jan  1  1970 tcl8.6
-rw-r--r-- 2 robert robert     7905 Jan  1  1970 tclConfig.sh
-rw-r--r-- 2 robert robert      773 Jan  1  1970 tclooConfig.sh
drwxr-xr-x 2 robert robert     4096 Jan  1  1970 tdbc1.1.1
drwxr-xr-x 2 robert robert     4096 Jan  1  1970 tdbcmysql1.1.1
drwxr-xr-x 2 robert robert     4096 Jan  1  1970 tdbcodbc1.1.1
drwxr-xr-x 2 robert robert     4096 Jan  1  1970 tdbcpostgres1.1.1
drwxr-xr-x 2 robert robert     4096 Jan  1  1970 thread2.8.5
```
I was initially having similar problems with TCL, but was able to resolve that by setting ``TCL_CONFIG=/app/lib``

**Comment by rderooy** [comment]
flatpak manifest

org.openmsx.openMSX.yaml
```
app-id: org.openmsx.openMSX
runtime: org.freedesktop.Platform
runtime-version: '20.08'
sdk: org.freedesktop.Sdk

command: openmsx

finish-args: # flatpak permissions
  - --device=all # needed for gamepads and serial/parallel
  - --share=ipc  # needed for X11
  - --share=network # needed for networking
  - --socket=x11
  - --socket=pulseaudio
  - --filesystem=home

cleanup:
  - /include
  - /lib/pkgconfig
  - /share/aclocal
  - /share/man
  - '*.la'
  - '*.a'
  - /share/doc

modules:

# Build Mesa GLU and GLEW
  - shared-modules/glu/glu-9.json
  - shared-modules/glew/glew.json

# Build TCL
  - name: tcl
    sources: 
      - type: archive
        url: https://downloads.sourceforge.net/project/tcl/Tcl/8.6.10/tcl8.6.10-src.tar.gz
        sha256: 5196dbf6638e3df8d5c87b5815c8c2b758496eb6f0e41446596c9a4e638d87ed
    subdir: unix
    build-options:
      no-debuginfo: true
    cleanup:
      - /bin
      - /man

# Build openMSX
  - name: openmsx
    sources:
      - type: archive
        url: https://github.com/openMSX/openMSX/releases/download/RELEASE_16_0/openmsx-16.0.tar.gz
        sha256: 055c6d12c8c15eb49be1ce53587f560e53fa05bdb05a56a7a249489fe93fb04e
      - type: file
        path: org.openmsx.openMSX.desktop
      - type: file
        path: org.openmsx.openMSX.metainfo.xml
      - type: shell
        commands:
          - sed -i 's/^INSTALL_BASE.*/INSTALL_BASE:=\/app\/share\/'${FLATPAK_ID}'/' build/custom.mk
          - sed -i "s/distroRoot = thirdPartyInstall or None/distroRoot = '\/app'/" build/probe.py
          - ln -s /usr/bin/libpng-config /app/bin/libpng-config
          - ln -s /usr/bin/sdl2-config /app/bin/sdl2-config
          - ln -s /usr/bin/pkg-config /app/bin/pkg-config
    build-options:
        env:
          - TCL_CONFIG=/app/lib
    post-install:
      - install -Dm755 /app/share/${FLATPAK_ID}/bin/openmsx /app/bin
      - install -Dm644 org.openmsx.openMSX.desktop /app/share/applications/${FLATPAK_ID}.desktop
      - install -Dm644 org.openmsx.openMSX.metainfo.xml /app/share/metainfo/${FLATPAK_ID}.metainfo.xml
      - install -Dm644 share/icons/openMSX-logo-16.png /app/share/icons/hicolor/16x16/apps/${FLATPAK_ID}.png
      - install -Dm644 share/icons/openMSX-logo-32.png /app/share/icons/hicolor/32x32/apps/${FLATPAK_ID}.png
      - install -Dm644 share/icons/openMSX-logo-48.png /app/share/icons/hicolor/48x48/apps/${FLATPAK_ID}.png
      - install -Dm644 share/icons/openMSX-logo-64.png /app/share/icons/hicolor/64x64/apps/${FLATPAK_ID}.png
      - install -Dm644 share/icons/openMSX-logo-128.png /app/share/icons/hicolor/128x128/apps/${FLATPAK_ID}.png
      - install -Dm644 share/icons/openMSX-logo-256.png /app/share/icons/hicolor/256x256/apps/${FLATPAK_ID}.png
    cleanup:
      - /app/share/${FLATPAK_ID}/bin/openmsx
      - /app/share/${FLATPAK_ID}/bin
      - /app/bin/libpng-config
      - /app/bin/pkg-config
      - /app/bin/sdl2-config

# Build wxWidgets (needed for Catapult)
  - name: wxwidgets
    sources:
      - type: archive
        url: https://github.com/wxWidgets/wxWidgets/releases/download/v3.0.5/wxWidgets-3.0.5.tar.bz2
        sha256: 8aacd56b462f42fb6e33b4d8f5d40be5abc3d3b41348ea968aa515cc8285d813
    build-options:
      cxxflags:
        -std=c++0x
    config-opts:
      - --with-opengl
      - --with-libjpeg
      - --with-expat
      - --with-libtiff
      - --with-libpng
      - --with-zlib
      - --disable-sdltest
      - --enable-unicode
      - --enable-display
      - --enable-propgrid
      - --disable-webkit
      - --disable-webview
      - --disable-webviewwebkit
      - --with-libiconv=/usr

# Build icoutils
  - name: icoutils
    config-opts:
      - --enable-maintainer-mode
    sources:
      - type: archive
        url: https://savannah.nongnu.org/download/icoutils/icoutils-0.32.3.tar.bz2
        sha256: 17abe02d043a253b68b47e3af69c9fc755b895db68fdc8811786125df564c6e0
      - type: shell
        commands:
          - cp -p /usr/share/automake-*/config.{sub,guess} "build-aux"/;
          - autoreconf -vfi;
    cleanup: ['*']

# Build openMSX Catapult launcher
  - name: catapult
    sources:
      - type: archive
        url: https://github.com/openMSX/openMSX/releases/download/RELEASE_16_0/openmsx-catapult-16.0.tar.gz
        sha256: fb2999d5c2af0e212f3653f40ee17a2807fc052403554dea720dbc30c9bbae94
      - type: file
        path: org.openmsx.openMSX.Catapult.desktop
      - type: shell
        commands:
          - sed -i 's/^INSTALL_BASE.*/INSTALL_BASE:=\/app\/share\/'${FLATPAK_ID}'.Catapult/' build/custom.mk
          - sed -i 's/^CATAPULT_OPENMSX_BINARY.*/CATAPULT_OPENMSX_BINARY:=\/app\/bin\/openmsx/' build/custom.mk
          - sed -i 's/^CATAPULT_OPENMSX_SHARE.*/CATAPULT_OPENMSX_SHARE:=\/app\/share\/'${FLATPAK_ID}'/' build/custom.mk
    buildsystem: simple
    build-commands:
      - make
      - make install
    post-install:
      - install -Dm755 /app/share/org.openmsx.openMSX.Catapult/bin/catapult /app/bin/openmsx-catapult
      - install -Dm644 org.openmsx.openMSX.Catapult.desktop /app/share/applications/${FLATPAK_ID}.Catapult.desktop
      - mkdir icons ; icotool -x -b 32 -o icons src/catapult.ico
      - install -Dm644 icons/catapult_14_16x16x32.png /app/share/icons/hicolor/16x16/apps/${FLATPAK_ID}.Catapult.png
      - install -Dm644 icons/catapult_3_32x32x32.png /app/share/icons/hicolor/32x32/apps/${FLATPAK_ID}.Catapult.png
      - install -Dm644 icons/catapult_4_48x48x32.png /app/share/icons/hicolor/48x48/apps/${FLATPAK_ID}.Catapult.png
      - install -Dm644 icons/catapult_6_64x64x32.png /app/share/icons/hicolor/64x64/apps/${FLATPAK_ID}.Catapult.png
      - install -Dm644 icons/catapult_1_128x128x32.png /app/share/icons/hicolor/128x128/apps/${FLATPAK_ID}.Catapult.png
    cleanup:
      - /app/share/org.openmsx.openMSX.Catapult/bin
```

The shared-modules referenced above can be found here:
https://github.com/flathub/shared-modules
